import { createContext, useContext, useEffect, useMemo, useState } from "react";

const dictionary = {
  en: {
    appName: "Disease AI",
    appSubtitle: "Decision Tree SaaS",
    medicalWorkspace: "Medical analytics workspace",
    loginHeroTitle: "Decision Tree predictions with traceable analytics.",
    loginHeroBody: "Upload Excel datasets, train transparent models, inspect trends, and export operational reports.",
    dashboard: "Dashboard",
    upload: "Upload Dataset",
    train: "Train Model",
    predict: "Prediction",
    analytics: "Analytics",
    reports: "Reports",
    admin: "Admin",
    logout: "Logout",
    login: "Login",
    register: "Create account",
    email: "Email",
    password: "Password",
    name: "Name",
    title: "Title",
    datasets: "Datasets",
    models: "Models",
    users: "Users",
    rows: "Rows",
    columns: "Columns",
    role: "Role",
    created: "Created",
    administrator: "Administrator",
    analyst: "Analyst",
    diseaseDistribution: "Disease distribution",
    monthlyTrends: "Monthly trends",
    weatherCorrelation: "Weather correlation",
    stateComparison: "State comparison",
    genderAnalysis: "Gender analysis",
    ageAnalysis: "Age group analysis",
    mortality: "Mortality analysis",
    chooseDataset: "Choose dataset",
    chooseModel: "Choose model",
    trainDecisionTree: "Train Decision Tree",
    exportPdf: "Export PDF",
    runPrediction: "Run prediction",
    riskLevel: "Risk level",
    recommendations: "Recommendations",
    loading: "Loading",
    noData: "No data yet",
    language: "Arabic",
    openNavigation: "Open navigation",
    closeNavigation: "Close navigation",
    firstAdmin: "The first registered user becomes an administrator.",
    authenticationFailed: "Authentication failed",
    uploadEmpty: "Upload a dataset to unlock charts, filters, and Decision Tree training.",
    supportedFormats: "Supported formats: .xls, .xlsx, .csv",
    datasetName: "Dataset name",
    excelFile: "Excel file",
    uploadFailed: "Upload failed",
    uploading: "Uploading...",
    analyze: "Analyze",
    notDetected: "Not detected",
    column: "Column",
    type: "Type",
    missing: "Missing",
    unique: "Unique",
    samples: "Samples",
    noChartData: "No chart data",
    filters: "Filters",
    clear: "Clear",
    state: "State",
    weather: "Weather",
    month: "Month",
    gender: "Gender",
    ageGroup: "Age group",
    disease: "Disease",
    cases: "Cases",
    deaths: "Deaths",
    select: "Select",
    auto: "Auto",
    modelName: "Model name",
    diseaseTarget: "Disease target",
    casesTarget: "Cases target",
    deathsTarget: "Deaths target",
    trainIntro: "Classifier for disease type and regressors for cases/deaths.",
    training: "Training...",
    trainingFailed: "Training failed",
    modelRuns: "Model runs",
    trainedModel: "Trained model",
    tree: "Tree",
    accuracy: "Accuracy",
    f1: "F1",
    casesMae: "Cases MAE",
    deathsMae: "Deaths MAE",
    predictIntro: "Enter environmental and medical factors for the selected model.",
    predictionFailed: "Prediction failed",
    predicting: "Predicting...",
    result: "Result",
    predictionHint: "Predictions will appear here after submitting features.",
    expectedCases: "Expected cases",
    expectedDeaths: "Expected deaths",
    riskLow: "Low",
    riskMedium: "Medium",
    riskHigh: "High",
    riskCritical: "Critical",
    reportIntro: "Generate a PDF summary with analytics and model metrics.",
    noModel: "No model",
    exporting: "Exporting...",
    pageNotFound: "Page not found",
    backToDashboard: "Back to dashboard"
  },
  ar: {
    appName: "ذكاء الأمراض",
    appSubtitle: "نظام شجرة القرار",
    medicalWorkspace: "مساحة التحليلات الطبية",
    loginHeroTitle: "تنبؤات شجرة قرار مع تحليلات قابلة للتتبع.",
    loginHeroBody: "ارفع ملفات Excel، ودرّب نماذج شفافة، وراجع الاتجاهات، وصدّر تقارير تشغيلية.",
    dashboard: "لوحة التحكم",
    upload: "رفع البيانات",
    train: "تدريب النموذج",
    predict: "التنبؤ",
    analytics: "التحليلات",
    reports: "التقارير",
    admin: "الإدارة",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم",
    title: "العنوان",
    datasets: "مجموعات البيانات",
    models: "النماذج",
    users: "المستخدمون",
    rows: "الصفوف",
    columns: "الأعمدة",
    role: "الدور",
    created: "تاريخ الإنشاء",
    administrator: "مدير النظام",
    analyst: "محلل",
    diseaseDistribution: "توزيع الأمراض",
    monthlyTrends: "الاتجاهات الشهرية",
    weatherCorrelation: "ارتباط الطقس",
    stateComparison: "مقارنة الولايات",
    genderAnalysis: "تحليل الجنس",
    ageAnalysis: "تحليل الفئات العمرية",
    mortality: "تحليل الوفيات",
    chooseDataset: "اختر مجموعة البيانات",
    chooseModel: "اختر النموذج",
    trainDecisionTree: "تدريب شجرة القرار",
    exportPdf: "تصدير PDF",
    runPrediction: "تشغيل التنبؤ",
    riskLevel: "مستوى الخطورة",
    recommendations: "التوصيات",
    loading: "جار التحميل",
    noData: "لا توجد بيانات بعد",
    language: "English",
    openNavigation: "فتح التنقل",
    closeNavigation: "إغلاق التنقل",
    firstAdmin: "أول مستخدم يتم تسجيله يصبح مدير النظام.",
    authenticationFailed: "فشل تسجيل الدخول",
    uploadEmpty: "ارفع مجموعة بيانات لعرض الرسوم، والفلاتر، وتدريب شجرة القرار.",
    supportedFormats: "الصيغ المدعومة: .xls و .xlsx و .csv",
    datasetName: "اسم مجموعة البيانات",
    excelFile: "ملف Excel",
    uploadFailed: "فشل رفع الملف",
    uploading: "جار الرفع...",
    analyze: "تحليل",
    notDetected: "لم يتم التعرف عليه",
    column: "العمود",
    type: "النوع",
    missing: "القيم المفقودة",
    unique: "القيم الفريدة",
    samples: "عينات",
    noChartData: "لا توجد بيانات للرسم",
    filters: "الفلاتر",
    clear: "مسح",
    state: "الولاية",
    weather: "الطقس",
    month: "الشهر",
    gender: "الجنس",
    ageGroup: "الفئة العمرية",
    disease: "المرض",
    cases: "الحالات",
    deaths: "الوفيات",
    select: "اختر",
    auto: "تلقائي",
    modelName: "اسم النموذج",
    diseaseTarget: "هدف المرض",
    casesTarget: "هدف الحالات",
    deathsTarget: "هدف الوفيات",
    trainIntro: "مصنف لنوع المرض ونماذج انحدار للحالات والوفيات.",
    training: "جار التدريب...",
    trainingFailed: "فشل التدريب",
    modelRuns: "تشغيلات النماذج",
    trainedModel: "النموذج المدرّب",
    tree: "الشجرة",
    accuracy: "الدقة",
    f1: "درجة F1",
    casesMae: "MAE للحالات",
    deathsMae: "MAE للوفيات",
    predictIntro: "أدخل العوامل البيئية والطبية للنموذج المحدد.",
    predictionFailed: "فشل التنبؤ",
    predicting: "جار التنبؤ...",
    result: "النتيجة",
    predictionHint: "ستظهر التنبؤات هنا بعد إرسال العوامل.",
    expectedCases: "الحالات المتوقعة",
    expectedDeaths: "الوفيات المتوقعة",
    riskLow: "منخفض",
    riskMedium: "متوسط",
    riskHigh: "مرتفع",
    riskCritical: "حرج",
    reportIntro: "إنشاء ملخص PDF يتضمن التحليلات ومقاييس النموذج.",
    noModel: "بدون نموذج",
    exporting: "جار التصدير...",
    pageNotFound: "الصفحة غير موجودة",
    backToDashboard: "العودة إلى لوحة التحكم"
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem("language") || "en");

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const value = useMemo(() => {
    const t = (key) => dictionary[language][key] || dictionary.en[key] || key;
    return {
      language,
      isRtl: language === "ar",
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "ar" : "en")),
      t
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
