const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const { v4: uuidv4 } = require("uuid");
const env = require("../config/env");

fs.mkdirSync(env.reportDir, { recursive: true });

function writeSection(doc, title, rows) {
  doc.moveDown().fontSize(15).fillColor("#0f766e").text(title);
  doc.moveDown(0.4).fontSize(10).fillColor("#111827");
  rows.forEach((row) => doc.text(row));
}

function createReport({ dataset, modelRun, analytics, user }) {
  const filename = `report-${uuidv4()}.pdf`;
  const reportPath = path.join(env.reportDir, filename);
  const doc = new PDFDocument({ margin: 48 });
  doc.pipe(fs.createWriteStream(reportPath));

  doc.fontSize(20).fillColor("#0f172a").text("Disease Prediction & Data Analysis Report", { align: "center" });
  doc.moveDown().fontSize(10).fillColor("#475569").text(`Generated: ${new Date().toLocaleString()}`);
  doc.text(`Generated by: ${user.name} (${user.email})`);

  writeSection(doc, "Dataset", [
    `Name: ${dataset.name}`,
    `Rows: ${dataset.rowCount}`,
    `Columns: ${dataset.columnCount}`,
    `Detected disease column: ${dataset.detectedColumns?.disease || "N/A"}`,
    `Detected cases column: ${dataset.detectedColumns?.cases || "N/A"}`,
    `Detected deaths column: ${dataset.detectedColumns?.deaths || "N/A"}`
  ]);

  if (modelRun) {
    writeSection(doc, "Model", [
      `Model: ${modelRun.name}`,
      `ML model ID: ${modelRun.mlModelId}`,
      `Available predictions: ${(modelRun.availablePredictions || []).join(", ")}`,
      `Metrics: ${JSON.stringify(modelRun.metrics, null, 2)}`
    ]);
  }

  writeSection(doc, "Analytics Summary", [
    `Top diseases: ${(analytics.disease_distribution || []).slice(0, 5).map((item) => `${item.label} (${item.cases})`).join(", ") || "N/A"}`,
    `Top states: ${(analytics.state_comparison || []).slice(0, 5).map((item) => `${item.label} (${item.cases})`).join(", ") || "N/A"}`,
    `Mortality: ${(analytics.mortality_analysis || []).slice(0, 5).map((item) => `${item.label} (${item.mortality_rate})`).join(", ") || "N/A"}`
  ]);

  doc.end();
  return { filename, path: reportPath };
}

module.exports = { createReport };
